// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// calCo
NumericVector calCo(NumericMatrix prev_atoms, double length, double bAngle, double tAngle);
RcppExport SEXP _compass_calCo(SEXP prev_atomsSEXP, SEXP lengthSEXP, SEXP bAngleSEXP, SEXP tAngleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type prev_atoms(prev_atomsSEXP);
    Rcpp::traits::input_parameter< double >::type length(lengthSEXP);
    Rcpp::traits::input_parameter< double >::type bAngle(bAngleSEXP);
    Rcpp::traits::input_parameter< double >::type tAngle(tAngleSEXP);
    rcpp_result_gen = Rcpp::wrap(calCo(prev_atoms, length, bAngle, tAngle));
    return rcpp_result_gen;
END_RCPP
}
// RMSD
double RMSD(Eigen::MatrixXd x, Eigen::MatrixXd y);
RcppExport SEXP _compass_RMSD(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type x(xSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(RMSD(x, y));
    return rcpp_result_gen;
END_RCPP
}
// LRMSD
List LRMSD(Eigen::MatrixXd xr, Eigen::MatrixXd yr);
RcppExport SEXP _compass_LRMSD(SEXP xrSEXP, SEXP yrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type xr(xrSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type yr(yrSEXP);
    rcpp_result_gen = Rcpp::wrap(LRMSD(xr, yr));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_compass_calCo", (DL_FUNC) &_compass_calCo, 4},
    {"_compass_RMSD", (DL_FUNC) &_compass_RMSD, 2},
    {"_compass_LRMSD", (DL_FUNC) &_compass_LRMSD, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_compass(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
