# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate Cartesian coordinates for 1-4 bonded atoms
#' 
#' @description 
#' Given coordinates for the first three atoms forming a dihedral,
#' the dihedral angle, bond angle, and bond length, calculate the coordinates
#' of the fourth atom forming the dihedral.
#'
#' @param prev_atoms a 3x3 matrix of coordinates for atoms 1-2-3 in dihedral, listed by row
#' @param length bond length between atoms 3-4 in dihedral 
#' @param bAngle planar bond angle between atoms 2-3-4
#' @param tAngle dihedral angle formed by atoms 1-2-3-4
#' 
#' @return
#' Returns the vector of coordinates for the fourth atom in the dihedral
#' 
calCo <- function(prev_atoms, length, bAngle, tAngle) {
    .Call(`_compass_calCo`, prev_atoms, length, bAngle, tAngle)
}

RMSD <- function(x, y) {
    .Call(`_compass_RMSD`, x, y)
}

LRMSD <- function(xr, yr) {
    .Call(`_compass_LRMSD`, xr, yr)
}

